import os
import sys
import io
import time
import traceback
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

from src.graph_state import GraphState
from src.data_cleaner import DataCleaner
from src.nodes.orchestrator import OrchestratorNode

class Workers:
    """
    WORKER AGENTS:
    Collection of specialized worker agents responsible for data cleaning, safe execution,
    visualization, and ambiguity resolution.
    """

    @staticmethod
    def data_cleaner_worker(state: GraphState) -> GraphState:
        """Worker 1: Data Cleaning & Preprocessing Worker"""
        cleaner = DataCleaner()
        df, report = cleaner.load_and_clean()
        state["cleaned_df"] = df
        state["data_audit_report"] = report

        return OrchestratorNode.log_step(
            state,
            node_name="DATA_CLEANING_WORKER",
            action="Clean & Standardize Dataset",
            details={
                "initial_rows": report["initial_rows"],
                "final_rows": report["final_rows"],
                "nulls_fixed": report["nulls_fixed"],
                "channels": report["channels_unified"]
            }
        )

    @staticmethod
    def query_executor_worker(state: GraphState) -> GraphState:
        """Worker 2: Safe Python / Pandas Query Execution Worker"""
        df = state.get("cleaned_df")
        code = state.get("generated_code", "")
        
        if df is None:
            cleaner = DataCleaner()
            df, report = cleaner.load_and_clean()
            state["cleaned_df"] = df

        if not code or code.strip() == "":
            state["execution_success"] = False
            state["execution_error"] = "No pandas code was generated by the planner."
            return state

        state["code_execution_count"] += 1
        
        # Sandbox Execution Environment
        sandbox_globals = {
            "df": df.copy(),
            "pd": pd,
            "np": np,
            "result": None
        }

        old_stdout = sys.stdout
        captured_output = io.StringIO()
        sys.stdout = captured_output

        exec_success = False
        exec_error = None
        result_data = None

        try:
            exec(code, sandbox_globals)
            exec_success = True
            result_data = sandbox_globals.get("result")
        except Exception as e:
            exec_error = f"{type(e).__name__}: {str(e)}\n{traceback.format_exc()}"
            exec_success = False
        finally:
            sys.stdout = old_stdout

        output_str = captured_output.getvalue().strip()

        state["execution_success"] = exec_success
        state["execution_error"] = exec_error
        state["execution_output_str"] = output_str
        state["execution_result_data"] = result_data

        # Record audit item
        audit_item = {
            "attempt": state["code_execution_count"],
            "code": code,
            "success": exec_success,
            "output": output_str,
            "error": exec_error
        }
        state["audit_trail"].append(audit_item)

        return OrchestratorNode.log_step(
            state,
            node_name="QUERY_EXECUTOR_WORKER",
            action=f"Execute Code (Attempt {state['code_execution_count']})",
            details={
                "success": exec_success,
                "output_length": len(output_str),
                "has_error": bool(exec_error)
            }
        )

    @staticmethod
    def visualization_worker(state: GraphState) -> GraphState:
        """Worker 3: Dynamic Chart Generator Worker"""
        if not state.get("requires_chart", False) or not state.get("execution_success", False):
            return state

        df = state.get("cleaned_df")
        if df is None:
            return state

        charts_dir = os.path.join(os.path.dirname(__file__), "..", "..", "charts")
        os.makedirs(charts_dir, exist_ok=True)
        chart_filename = f"chart_{int(time.time())}.png"
        chart_path = os.path.join(charts_dir, chart_filename)

        category = state.get("intent_category", "general")

        plt.style.use('dark_background')
        fig, ax = plt.subplots(figsize=(9, 4.5), dpi=150)
        fig.patch.set_facecolor('#0f172a')
        ax.set_facecolor('#1e293b')

        try:
            if category == "trend":
                # Weekly or daily trend
                df['month_week'] = df['date'].dt.strftime('%Y-W%U')
                weekly = df.groupby('month_week')['cpa'].mean().reset_index()
                ax.plot(weekly['month_week'], weekly['cpa'], marker='o', color='#38bdf8', linewidth=2.5, label='Avg CPA (INR)')
                ax.set_title("CTR / CPA Weekly Performance Trend", color='white', fontsize=12, pad=12)
                ax.set_ylabel("CPA (INR)", color='white')
                plt.xticks(rotation=45, ha='right', color='white')

            elif category == "comparison":
                # Channel comparison
                comp = df[df['channel'].isin(['Meta', 'Google Search'])].groupby('channel')['cpa'].mean().reset_index()
                sns.barplot(data=comp, x='channel', y='cpa', palette=['#3b82f6', '#10b981'], ax=ax)
                ax.set_title("Meta vs Google Search CPA Comparison", color='white', fontsize=12, pad=12)
                ax.set_ylabel("Cost Per Conversion (INR)", color='white')

            elif category == "ranking":
                # City / Creative / Age Group Ranking
                group = df.groupby('city')['cpa'].mean().sort_values(ascending=False).head(7).reset_index()
                sns.barplot(data=group, x='cpa', y='city', palette='magma', ax=ax)
                ax.set_title("Top Cities by Highest Cost Per Conversion (CPA)", color='white', fontsize=12, pad=12)
                ax.set_xlabel("CPA (INR)", color='white')

            else:
                # Default channel performance breakdown
                group = df.groupby('channel')['spend_inr'].sum().reset_index()
                ax.pie(group['spend_inr'], labels=group['channel'], autopct='%1.1f%%', colors=['#38bdf8', '#818cf8', '#c084fc', '#f472b6', '#fb7185'])
                ax.set_title("Total Spend Distribution by Channel", color='white', fontsize=12, pad=12)

            plt.tight_layout()
            plt.savefig(chart_path, bbox_inches='tight', facecolor=fig.get_facecolor(), edgecolor='none')
            plt.close(fig)

            state["chart_path"] = chart_path
            state["chart_title"] = f"{category.title()} Diagnostic Visualization"

        except Exception as e:
            plt.close('all')
            state["chart_path"] = None

        return OrchestratorNode.log_step(
            state,
            node_name="VISUALIZATION_WORKER",
            action="Generate Diagnostic Chart",
            details={"chart_path": state.get("chart_path")}
        )

    @staticmethod
    def ambiguity_clarifier_worker(state: GraphState) -> GraphState:
        """Worker 4: Ambiguity Clarification & Dialog Worker"""
        prompt = state.get("clarification_prompt", "The question contains ambiguous parameters.")
        options = state.get("clarification_options", [])

        state["final_answer"] = f"### ⚠️ Ambiguous Question Identified\n\n{prompt}\n\n**Suggested Clarification Options:**\n" + "\n".join([f"- {opt}" for opt in options])

        return OrchestratorNode.log_step(
            state,
            node_name="AMBIGUITY_CLARIFIER_WORKER",
            action="Formulate Clarification Prompt",
            details={"prompt": prompt, "options": options}
        )
